
/**************************************************************
 *	
 *	mus_win, 8 bit, 11025Hz,
 *	1 channel, 2733395 bytes/channel
 *	Total Size: 1 * 2733395 + 4 (header) = 2733439 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\music\mus_win.wav
 *	Time-stamp: Tue Apr 21 14:27:14 2020
 *	
 **************************************************************/

#ifndef __MUS_WINH__
#define __MUS_WINH__

#define MUS_WINFREQ 11025
#define MUS_WINLEN 2733395

extern const unsigned char mus_win[2733395];

#endif /* __MUS_WINH__ */
