
/**************************************************************
 *	
 *	mus_game2, 8 bit, 11025Hz,
 *	1 channel, 2733395 bytes/channel
 *	Total Size: 1 * 2733395 + 4 (header) = 2733439 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\music\mus_game2.wav
 *	Time-stamp: Mon Apr 20 21:34:58 2020
 *	
 **************************************************************/

#ifndef __MUS_GAME2H__
#define __MUS_GAME2H__

#define MUS_GAME2FREQ 11025
#define MUS_GAME2LEN 2733395

extern const unsigned char mus_game2[2733395];

#endif /* __MUS_GAME2H__ */
