
/**************************************************************
 *	
 *	mus_start, 8 bit, 11025Hz,
 *	1 channel, 816943 bytes/channel
 *	Total Size: 1 * 816943 + 4 (header) = 816987 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\music\mus_start.wav
 *	Time-stamp: Mon Apr 20 21:20:50 2020
 *	
 **************************************************************/

#ifndef __MUS_STARTH__
#define __MUS_STARTH__

#define MUS_STARTFREQ 11025
#define MUS_STARTLEN 816943

extern const unsigned char mus_start[816943];

#endif /* __MUS_STARTH__ */
