
/**************************************************************
 *	
 *	mus_game2, 8 bit, 11025Hz,
 *	1 channel, 819474 bytes/channel
 *	Total Size: 1 * 819474 + 4 (header) = 819518 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\music\mus_game2.wav
 *	Time-stamp: Tue Apr 21 14:34:03 2020
 *	
 **************************************************************/

#ifndef __MUS_GAME2H__
#define __MUS_GAME2H__

#define MUS_GAME2FREQ 11025
#define MUS_GAME2LEN 819474

extern const unsigned char mus_game2[819474];

#endif /* __MUS_GAME2H__ */
