
/**************************************************************
 *	
 *	mus_game1, 8 bit, 11025Hz,
 *	1 channel, 1749550 bytes/channel
 *	Total Size: 1 * 1749550 + 4 (header) = 1749594 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\music\mus_game1.wav
 *	Time-stamp: Mon Apr 20 21:34:34 2020
 *	
 **************************************************************/

#ifndef __MUS_GAME1H__
#define __MUS_GAME1H__

#define MUS_GAME1FREQ 11025
#define MUS_GAME1LEN 1749550

extern const unsigned char mus_game1[1749550];

#endif /* __MUS_GAME1H__ */
