
/**************************************************************
 *	
 *	snd_Ding, 8 bit, 11025Hz,
 *	1 channel, 5200 bytes/channel
 *	Total Size: 1 * 5200 + 4 (header) = 5244 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\wavs\snd_Ding.wav
 *	Time-stamp: Mon Apr 20 15:52:56 2020
 *	
 **************************************************************/

#ifndef __SND_DINGH__
#define __SND_DINGH__

#define SND_DINGFREQ 11025
#define SND_DINGLEN 5200

extern const unsigned char snd_Ding[5200];

#endif /* __SND_DINGH__ */
