
/**************************************************************
 *	
 *	snd_Zap, 8 bit, 11025Hz,
 *	1 channel, 6061 bytes/channel
 *	Total Size: 1 * 6061 + 4 (header) = 6105 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Dev\CS2261Game\sound\wavs\snd_Zap.wav
 *	Time-stamp: Mon Apr 20 18:36:14 2020
 *	
 **************************************************************/

#ifndef __SND_ZAPH__
#define __SND_ZAPH__

#define SND_ZAPFREQ 11025
#define SND_ZAPLEN 6061

extern const unsigned char snd_Zap[6061];

#endif /* __SND_ZAPH__ */
